//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class information
    {
        public int user_id { get; set; }
        public string name { get; set; }
        public string nickname { get; set; }
        public string email_id { get; set; }
        public string gender { get; set; }
        public string age { get; set; }
        public string phone_no { get; set; }
        public string mobile_no { get; set; }
        public string profession { get; set; }
        public string address { get; set; }
    }
}
