//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class register_user
    {
        public int user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email_id { get; set; }
        public string remarks { get; set; }
    }
}
