//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Master
    {
        public int Supplier_ID { get; set; }
        public string Supplier_Name { get; set; }
        public string Supplier_Company { get; set; }
        public string Supplier_Email { get; set; }
        public string Supplier_Mobile { get; set; }
        public string Supplier_Phone { get; set; }
        public string Supplier_City { get; set; }
        public string Supplier_Address { get; set; }
    }
}
